name: Email Action Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 23f3001169@ds.study.iitm.ac.in
        run: echo "Hello from eShopCo action verification!"
